steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/aiwaverider-backend-460819/cloud-run-source-deploy/aiwaverider-backend-service:latest', '-f', 'Dockerfile.cloudrun', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/aiwaverider-backend-460819/cloud-run-source-deploy/aiwaverider-backend-service:latest']
images:
  - 'europe-west1-docker.pkg.dev/aiwaverider-backend-460819/cloud-run-source-deploy/aiwaverider-backend-service:latest' 