FROM postgres:16-alpine
COPY migration/001_schema.sql /docker-entrypoint-initdb.d/001_schema.sql
COPY migration/002_indices.sql /docker-entrypoint-initdb.d/002_indices.sql
COPY migration/003_seed.sql /docker-entrypoint-initdb.d/003_seed.sql
COPY migration/004_apps.sql /docker-entrypoint-initdb.d/004_apps.sql
COPY migration/005_skool_downloads.sql /docker-entrypoint-initdb.d/005_skool_downloads.sql
COPY migration/006_email_templates.sql /docker-entrypoint-initdb.d/006_email_templates.sql
COPY migration/007_notifications.sql /docker-entrypoint-initdb.d/007_notifications.sql
